### PR TITLE
Additions of New Tags Permission to Android

### PR DESCRIPTION
**Pull request by KelvnPere**
Based on the title, there were some new permissions that were added which includes "stream-team-videos" and "stream-personal-videos" which was causing some users to not have access to some contents. Also, 2 tests were written to verify the permission checks during the login session.

Here is a link to the issue https://github.com/razeware/emitron-Android/issues/352

### CODE REVIEW

**Review by sammyd — APPROVED** [review]
:+1: Not sure I follow it completely, but it seems ok to me at first glance. Thanks!

**Comment by KelvnPere** [comment]
> 👍 Not sure I follow it completely, but it seems ok to me at first glance. Thanks!

Its there a way to actually test it, with user accounts? @sammyd

**Comment by sammyd** [comment]
If you sign up for a new kodeco account, I can give you the new permissions and you can give it a try?

**Comment by KelvnPere** [comment]
> If you sign up for a new kodeco account, I can give you the new permissions and you can give it a try?

Here is the new account, LMK when you have done it. Also where in particular should test it in the app?

Username: @dev_testing

**Comment by KelvnPere** [comment]
> > If you sign up for a new kodeco account, I can give you the new permissions and you can give it a try?
> 
> Here is the new account, LMK when you have done it. Also where in particular should test it in the app?
> 
> Username: @dev_testing

@sammyd Not sure if you missed this, have the access been granted to the account?

**Comment by sammyd** [comment]
@KelvnPere So sorry for the delay—I've been out of the office this week. This account should now have the required access.

**Comment by KelvnPere** [comment]
> @KelvnPere So sorry for the delay—I've been out of the office this week. This account should now have the required access.

No issues, that's totally fine. Can you provide me like a keyword search so i can fully test the app with that account. In other words, the videos that one with that access should have access to. Thanks

@sammyd

**Comment by KelvnPere** [comment]
> 

@sammyd still waiting on you for the above. Thanks

**Comment by sammyd** [comment]
@KelvnPere sorry I completely missed this comment. That account should have access to all videos.

**Comment by KelvnPere** [comment]
@sammyd I have tested it from my end and it looks good. Also, i think the dev_testing in the collection page was showing some contents locked which i feel has to do with the correct permissions. When i tested it with my normal work kodeco account it showed correctly and fine.

This is good from my end.

**Comment by KelvnPere** [comment]
@sammyd

**Pull request merged**
