### PR TITLE
Update Room to Support M1 Macbooks 

### PR DESCRIPTION
**Pull request by jumaallan**
Fixes Room Issue #340  when running the project on an M1 Mac

**Some notes:**

This might need to ship as is, since updating to the latest Room version means we need to target sdk 31. This introduces more changes which are out of scope for this PR

### CODE REVIEW

**Comment by sammyd** [comment]
@wangerekaharun could you take a look at this PR please, once you've got the updates you've been working on integrated? Thanks!

**Review by wangerekaharun — APPROVED** [review]

**Comment by wangerekaharun** [comment]
> @wangerekaharun could you take a look at this PR please, once you've got the updates you've been working on integrated? Thanks!

@sammyd this can be merged, so that I can pull the changes.

**Comment by sammyd** [comment]
@jumaallan thanks so much for this. Sadly, I've just merged a pretty big PR to address a login issue to development, and there are now some conflicts. Would you be able to resolve these conflicts and ask for another review please? Thanks!

**Comment by jumaallan** [comment]
@sammyd I have fixed the small conflicts. Should be ready for review again

**Comment by jumaallan** [comment]
@sammyd / @wangerekaharun Ping

The CI failure is related to keystore config missing. You can take a look at this @wangerekaharun

**Comment by wangerekaharun** [comment]
I'll look into this @jumaallan also you can pull the development branch since I raised a PR and CI was not failing.

**Pull request closed without merging**
